# Generated by Django 3.2.16 on 2023-01-28 23:13

import apps.blog.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('blog', '0006_auto_20230124_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=126, null=True)),
                ('thumbnail', models.ImageField(blank=True, max_length=600, null=True, upload_to=apps.blog.models.blog_thumbnail_directory)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=126, unique=True)),
                ('description', models.TextField(blank=True, max_length=252, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category')),
            ],
        ),
    ]
