export const GET_CASES_LIST_SUCCESS = ' GET_CASES_LIST_SUCCESS'
export const GET_CASES_LIST_FAIL = ' GET_CASES_LIST_FAIL'
export const GET_CASE_SUCCESS = 'GET_CASE_SUCCESS '
export const GET_CASE_FAIL = ' GET_CASE_FAIL'